# $Id: Makefile,v 1.2 2006/03/08 03:58:56 sfmao Exp $

include Makefile.component
include ../../MakeXbowlocal
# Automatically add certain command-line goals:
GOALS += binlink
include $(MAKERULES)





