/*
 * Copyright (c) 2004-2007 Crossbow Technology, Inc.
 * Copyright (c) 2002-2005 Intel Corporation
 * Copyright (c) 2000-2005 The Regents of the University of California
 * All rights reserved.
 * See license.txt file included with the distribution.
 *
 * $Id: sensorboard.h,v 1.2.4.1 2007/04/27 05:30:38 njain Exp $
 */

/**
 * @author Mike Grimmer
 */
#define TOS_MAG_POT_ADDR  0
#define TOS_MIC_POT_ADDR  1
#define TOS_PIR_POT_ADDR  1
#define TOS_LPF_POT_ADDR  3
#define TOS_HPF_POT_ADDR  2

#define PIR_INT_ENABLE()  sbi(EIMSK,6)
#define PIR_INT_DISABLE() cbi(EIMSK,6)

TOSH_ASSIGN_PIN(ALE,  G, 2);
TOSH_ASSIGN_PIN(PWM0,   B, 4);
TOSH_ASSIGN_PIN(PWM1A,   B, 5);
TOSH_ASSIGN_PIN(PWM1B,   B, 6);
TOSH_ASSIGN_PIN(AC_P,  E, 2);
TOSH_ASSIGN_PIN(AC_N,  E, 3);
TOSH_ASSIGN_PIN(MAG_SR,  A, 5);



enum {
  TOSH_ACTUAL_PHOTO_PORT = 1,
  TOSH_ACTUAL_MIC_PORT = 2, 
  TOSH_ACTUAL_ACCEL_X_PORT = 3, 
  TOSH_ACTUAL_ACCEL_Y_PORT = 4,
  TOSH_ACTUAL_MAG_X_PORT = 5, 
  TOSH_ACTUAL_MAG_Y_PORT = 6,  
  TOSH_ACTUAL_PIR_PORT = 7
};

enum {
  TOS_ADC_PHOTO_PORT = 1,
  TOS_ADC_MIC_PORT = 2,
  TOS_ADC_ACCEL_X_PORT = 3,
  TOS_ADC_ACCEL_Y_PORT = 4,
  TOS_ADC_MAG_X_PORT = 5,
  TOS_ADC_MAG_Y_PORT = 6,
  TOS_ADC_PIR_PORT = 7
};


TOSH_ALIAS_PIN(PHOTO_CTL, PW0);
TOSH_ALIAS_PIN(ACCEL_CTL, PW4);
TOSH_ALIAS_OUTPUT_ONLY_PIN(MIC_CTL, PW3);
TOSH_ALIAS_OUTPUT_ONLY_PIN(SOUNDER_CTL, PW2)
TOSH_ALIAS_PIN(MAG_CTL, PW5);
TOSH_ALIAS_OUTPUT_ONLY_PIN(PIR_CTL, PW6);
TOSH_ALIAS_PIN(I2C_MUX, ALE);
TOSH_ALIAS_PIN(PIR_DETECT, INT2);
TOSH_ALIAS_PIN(AUDIO_DETECT, INT1);
TOSH_ALIAS_PIN(IRQUAD1, PWM0);
TOSH_ALIAS_PIN(IRQUAD2, PWM1A);
TOSH_ALIAS_PIN(IRQUAD3, AC_P);
TOSH_ALIAS_PIN(IRQUAD4, AC_N);
