# $Id: Makefile.component,v 1.3 2006/01/09 20:48:33 rkapur Exp $

COMPONENT=XMeshBase
MSG_SIZE=55

INCLUDES += -I${TOSROOT}/tos/lib/XHeartbeat
#INCLUDES += -I${TOSROOT}/tos/lib/XJoin
#DEFINES+= -DJOIN_BASE
#CFLAGS += -DFEATURE_HEARTBEAT

