# $Id: Makefile,v 1.3 2006/03/08 03:58:27 sfmao Exp $
include Makefile.component
include ../../MakeXbowlocal

# Automatically add certain command-line goals:
GOALS += basic freq route,hp base binlink
include $(MAKERULES)
DEFINES += -DMHOP_QUEUE_SIZE=12


