# $Id: Makefile.component,v 1.1 2006/01/03 07:41:55 mturon Exp $

COMPONENT=TestSensor
SENSORBOARD=mep410
MSG_SIZE=49
PFLAGS += -I$(XBOWROOT)/sensorboards/$(SENSORBOARD) -I$(TOSROOT)/tos/sensorboards/micawb